name: PyPI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pytest
        run: pip install pytest
      - name: Unit tests
        run: pytest

  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install twine wheel
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Twine checks
        run: twine check dist/*
      - name: Twine upload
        run: twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
